(function () {
  // Map ids MUST match the game's GameMapType folder ids (resources/maps/<id>),
  // because auto-join matches a public lobby by normalizing map.id / map.name
  // against the lobby's map fields, and private-lobby scenarios are created with
  // map.id as the mapId. Kept in sync with OpenFront v0.32.3 (the v32 release
  // added 20 maps). `thumbnail` is legacy/unused — the settings popup resolves
  // thumbnails live via mapThumbnailUrl(map.id) against the game's asset
  // manifest; a missing manifest entry just degrades to a placeholder glyph.
  //
  // Excluded on purpose: "unitedstates" (present in the game repo but NOT in the
  // production asset manifest yet, so it has no thumbnail and is not in the live
  // lobby rotation). Tournament maps (tourney1..4) and special variants
  // (baikalnukewars, europeclassic, giantworldmap) are included for
  // completeness, but tourney/special maps rarely or never appear in public
  // auto-join lobbies.
  const maps = [
    { id: "achiran", name: "Achiran", thumbnail: "assets/map-thumbnails/achiran/thumbnail.webp" },
    { id: "aegean", name: "Aegean", thumbnail: "assets/map-thumbnails/aegean/thumbnail.webp" },
    { id: "africa", name: "Africa", thumbnail: "assets/map-thumbnails/africa/thumbnail.webp" },
    { id: "alps", name: "Alps", thumbnail: "assets/map-thumbnails/alps/thumbnail.webp" },
    { id: "amazonriver", name: "Amazon River", thumbnail: "assets/map-thumbnails/amazonriver/thumbnail.webp" },
    { id: "antarctica", name: "Antarctica", thumbnail: "assets/map-thumbnails/antarctica/thumbnail.webp" },
    { id: "archipelagosea", name: "Archipelago Sea", thumbnail: "assets/map-thumbnails/archipelagosea/thumbnail.webp" },
    { id: "arctic", name: "Arctic", thumbnail: "assets/map-thumbnails/arctic/thumbnail.webp" },
    { id: "asia", name: "Asia", thumbnail: "assets/map-thumbnails/asia/thumbnail.webp" },
    { id: "australia", name: "Australia", thumbnail: "assets/map-thumbnails/australia/thumbnail.webp" },
    { id: "baikal", name: "Baikal", thumbnail: "assets/map-thumbnails/baikal/thumbnail.webp" },
    { id: "baikalnukewars", name: "Baikal Nuke Wars", thumbnail: "assets/map-thumbnails/baikalnukewars/thumbnail.webp" },
    { id: "bajacalifornia", name: "Baja California", thumbnail: "assets/map-thumbnails/bajacalifornia/thumbnail.webp" },
    { id: "balkans", name: "Balkans", thumbnail: "assets/map-thumbnails/balkans/thumbnail.webp" },
    { id: "beringsea", name: "Bering Sea", thumbnail: "assets/map-thumbnails/beringsea/thumbnail.webp" },
    { id: "beringstrait", name: "Bering Strait", thumbnail: "assets/map-thumbnails/beringstrait/thumbnail.webp" },
    { id: "betweentwoseas", name: "Between Two Seas", thumbnail: "assets/map-thumbnails/betweentwoseas/thumbnail.webp" },
    { id: "blacksea", name: "Black Sea", thumbnail: "assets/map-thumbnails/blacksea/thumbnail.webp" },
    { id: "bosphorusstraits", name: "Bosphorus Straits", thumbnail: "assets/map-thumbnails/bosphorusstraits/thumbnail.webp" },
    { id: "britannia", name: "Britannia", thumbnail: "assets/map-thumbnails/britannia/thumbnail.webp" },
    { id: "britanniaclassic", name: "Britannia Classic", thumbnail: "assets/map-thumbnails/britanniaclassic/thumbnail.webp" },
    { id: "caribbean", name: "Caribbean", thumbnail: "assets/map-thumbnails/caribbean/thumbnail.webp" },
    { id: "caucasus", name: "Caucasus", thumbnail: "assets/map-thumbnails/caucasus/thumbnail.webp" },
    { id: "choppingblock", name: "Chopping Block", thumbnail: "assets/map-thumbnails/choppingblock/thumbnail.webp" },
    { id: "conakry", name: "Conakry", thumbnail: "assets/map-thumbnails/conakry/thumbnail.webp" },
    { id: "danishstraits", name: "Danish Straits", thumbnail: "assets/map-thumbnails/danishstraits/thumbnail.webp" },
    { id: "deglaciatedantarctica", name: "Deglaciated Antarctica", thumbnail: "assets/map-thumbnails/deglaciatedantarctica/thumbnail.webp" },
    { id: "didier", name: "Didier", thumbnail: "assets/map-thumbnails/didier/thumbnail.webp" },
    { id: "didierfrance", name: "Didier (France)", thumbnail: "assets/map-thumbnails/didierfrance/thumbnail.webp" },
    { id: "dyslexdria", name: "Dyslexdria", thumbnail: "assets/map-thumbnails/dyslexdria/thumbnail.webp" },
    { id: "eastasia", name: "East Asia", thumbnail: "assets/map-thumbnails/eastasia/thumbnail.webp" },
    { id: "europe", name: "Europe", thumbnail: "assets/map-thumbnails/europe/thumbnail.webp" },
    { id: "europeclassic", name: "Europe Classic", thumbnail: "assets/map-thumbnails/europeclassic/thumbnail.webp" },
    { id: "falklandislands", name: "Falkland Islands", thumbnail: "assets/map-thumbnails/falklandislands/thumbnail.webp" },
    { id: "faroeislands", name: "Faroe Islands", thumbnail: "assets/map-thumbnails/faroeislands/thumbnail.webp" },
    { id: "fourislands", name: "Four Islands", thumbnail: "assets/map-thumbnails/fourislands/thumbnail.webp" },
    { id: "gatewaytotheatlantic", name: "Gateway to the Atlantic", thumbnail: "assets/map-thumbnails/gatewaytotheatlantic/thumbnail.webp" },
    { id: "giantworldmap", name: "Giant World Map", thumbnail: "assets/map-thumbnails/giantworldmap/thumbnail.webp" },
    { id: "greatlakes", name: "Great Lakes", thumbnail: "assets/map-thumbnails/greatlakes/thumbnail.webp" },
    { id: "gulfofstlawrence", name: "Gulf of St. Lawrence", thumbnail: "assets/map-thumbnails/gulfofstlawrence/thumbnail.webp" },
    { id: "halkidiki", name: "Halkidiki", thumbnail: "assets/map-thumbnails/halkidiki/thumbnail.webp" },
    { id: "hawaii", name: "Hawaii", thumbnail: "assets/map-thumbnails/hawaii/thumbnail.webp" },
    { id: "hongkong", name: "Hong Kong", thumbnail: "assets/map-thumbnails/hongkong/thumbnail.webp" },
    { id: "iceland", name: "Iceland", thumbnail: "assets/map-thumbnails/iceland/thumbnail.webp" },
    { id: "indiansubcontinent", name: "Indian Subcontinent", thumbnail: "assets/map-thumbnails/indiansubcontinent/thumbnail.webp" },
    { id: "italia", name: "Italia", thumbnail: "assets/map-thumbnails/italia/thumbnail.webp" },
    { id: "japan", name: "Japan", thumbnail: "assets/map-thumbnails/japan/thumbnail.webp" },
    { id: "juandefucastrait", name: "Juan de Fuca Strait", thumbnail: "assets/map-thumbnails/juandefucastrait/thumbnail.webp" },
    { id: "korea", name: "Korea", thumbnail: "assets/map-thumbnails/korea/thumbnail.webp" },
    { id: "labyrinth", name: "Labyrinth", thumbnail: "assets/map-thumbnails/labyrinth/thumbnail.webp" },
    { id: "lemnos", name: "Lemnos", thumbnail: "assets/map-thumbnails/lemnos/thumbnail.webp" },
    { id: "lisbon", name: "Lisbon", thumbnail: "assets/map-thumbnails/lisbon/thumbnail.webp" },
    { id: "losangeles", name: "Los Angeles", thumbnail: "assets/map-thumbnails/losangeles/thumbnail.webp" },
    { id: "luna", name: "Luna", thumbnail: "assets/map-thumbnails/luna/thumbnail.webp" },
    { id: "manicouagan", name: "Manicouagan", thumbnail: "assets/map-thumbnails/manicouagan/thumbnail.webp" },
    { id: "marenostrum", name: "Mare Nostrum", thumbnail: "assets/map-thumbnails/marenostrum/thumbnail.webp" },
    { id: "mars", name: "Mars", thumbnail: "assets/map-thumbnails/mars/thumbnail.webp" },
    { id: "mena", name: "MENA", thumbnail: "assets/map-thumbnails/mena/thumbnail.webp" },
    { id: "middleeast", name: "Middle East", thumbnail: "assets/map-thumbnails/middleeast/thumbnail.webp" },
    { id: "milkyway", name: "Milky Way", thumbnail: "assets/map-thumbnails/milkyway/thumbnail.webp" },
    { id: "mississippiriver", name: "Mississippi River", thumbnail: "assets/map-thumbnails/mississippiriver/thumbnail.webp" },
    { id: "montreal", name: "Montreal", thumbnail: "assets/map-thumbnails/montreal/thumbnail.webp" },
    { id: "newyorkcity", name: "New York City", thumbnail: "assets/map-thumbnails/newyorkcity/thumbnail.webp" },
    { id: "niledelta", name: "Nile Delta", thumbnail: "assets/map-thumbnails/niledelta/thumbnail.webp" },
    { id: "northamerica", name: "North America", thumbnail: "assets/map-thumbnails/northamerica/thumbnail.webp" },
    { id: "northwestpassage", name: "Northwest Passage", thumbnail: "assets/map-thumbnails/northwestpassage/thumbnail.webp" },
    { id: "oceania", name: "Oceania", thumbnail: "assets/map-thumbnails/oceania/thumbnail.webp" },
    { id: "onion", name: "Onion", thumbnail: "assets/map-thumbnails/onion/thumbnail.webp" },
    { id: "pangaea", name: "Pangaea", thumbnail: "assets/map-thumbnails/pangaea/thumbnail.webp" },
    { id: "passage", name: "Passage", thumbnail: "assets/map-thumbnails/passage/thumbnail.webp" },
    { id: "pluto", name: "Pluto", thumbnail: "assets/map-thumbnails/pluto/thumbnail.webp" },
    { id: "sanfrancisco", name: "San Francisco", thumbnail: "assets/map-thumbnails/sanfrancisco/thumbnail.webp" },
    { id: "sierpinski", name: "Sierpinski", thumbnail: "assets/map-thumbnails/sierpinski/thumbnail.webp" },
    { id: "southamerica", name: "South America", thumbnail: "assets/map-thumbnails/southamerica/thumbnail.webp" },
    { id: "southeastasia", name: "Southeast Asia", thumbnail: "assets/map-thumbnails/southeastasia/thumbnail.webp" },
    { id: "straitofgibraltar", name: "Strait of Gibraltar", thumbnail: "assets/map-thumbnails/straitofgibraltar/thumbnail.webp" },
    { id: "straitofhormuz", name: "Strait of Hormuz", thumbnail: "assets/map-thumbnails/straitofhormuz/thumbnail.webp" },
    { id: "straitofmalacca", name: "Strait of Malacca", thumbnail: "assets/map-thumbnails/straitofmalacca/thumbnail.webp" },
    { id: "surrounded", name: "Surrounded", thumbnail: "assets/map-thumbnails/surrounded/thumbnail.webp" },
    { id: "svalmel", name: "Svalmel", thumbnail: "assets/map-thumbnails/svalmel/thumbnail.webp" },
    { id: "taiwanstrait", name: "Taiwan Strait", thumbnail: "assets/map-thumbnails/taiwanstrait/thumbnail.webp" },
    { id: "thebox", name: "The Box", thumbnail: "assets/map-thumbnails/thebox/thumbnail.webp" },
    { id: "titan", name: "Titan", thumbnail: "assets/map-thumbnails/titan/thumbnail.webp" },
    { id: "tourney1", name: "Tourney (2 Teams)", thumbnail: "assets/map-thumbnails/tourney1/thumbnail.webp" },
    { id: "tourney2", name: "Tourney (3 Teams)", thumbnail: "assets/map-thumbnails/tourney2/thumbnail.webp" },
    { id: "tourney3", name: "Tourney (4 Teams)", thumbnail: "assets/map-thumbnails/tourney3/thumbnail.webp" },
    { id: "tourney4", name: "Tourney (8 Teams)", thumbnail: "assets/map-thumbnails/tourney4/thumbnail.webp" },
    { id: "tradersdream", name: "Traders Dream", thumbnail: "assets/map-thumbnails/tradersdream/thumbnail.webp" },
    { id: "twolakes", name: "Two Lakes", thumbnail: "assets/map-thumbnails/twolakes/thumbnail.webp" },
    { id: "venice", name: "Venice", thumbnail: "assets/map-thumbnails/venice/thumbnail.webp" },
    { id: "warshipwarship", name: "Warship Warship", thumbnail: "assets/map-thumbnails/warshipwarship/thumbnail.webp" },
    { id: "world", name: "World", thumbnail: "assets/map-thumbnails/world/thumbnail.webp" },
    { id: "worldinverted", name: "World Inverted", thumbnail: "assets/map-thumbnails/worldinverted/thumbnail.webp" },
    { id: "yellowsea", name: "Yellow Sea", thumbnail: "assets/map-thumbnails/yellowsea/thumbnail.webp" },
    { id: "yenisei", name: "Yenisei", thumbnail: "assets/map-thumbnails/yenisei/thumbnail.webp" },
  ];

  globalThis.OPENFRONT_MAPS = Object.freeze(maps);
})();
